version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
     - nginx-proxy
     - default



  master:
#    image: jiller/jiller-manager
    build: .
    command: ./run.sh
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - VIRTUAL_HOST=www.jiller.loc,jiller.loc,f3de2c32.ngrok.io,www.f3de2c32.ngrok.io
      - DOCKER_HOST=unix:///tmp/docker.sock
    expose:
      - 8000
 


networks:
  nginx-proxy:
     external:
       name: nginx-proxy
