# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='admin_name',
            field=models.CharField(default=1, max_length=20, verbose_name='Admin name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='admin_pass',
            field=models.CharField(default=1, max_length=20, verbose_name='Admin password'),
            preserve_default=False,
        ),
    ]
